const Cars = [
  {
    id: 0,
    title: "Model S",
    description: "Order Online for",
    delivery: "Touchless Delivery",
    image: "images/model-s.jpg",
    range: "390",
    time: "1.99",
    topSpeed: "200",
    peakPower: "1,020",
    order: "Custom Order",
    inventory: "existing inventory",
    downArrow: true,
  },
  {
    id: 1,
    title: "Model 3",
    description: "Order Online for",
    delivery: "Touchless Delivery",
    image: "images/model-3.jpg",
    range: "400",
    time: "2.99",
    topSpeed: "180",
    peakPower: "900",
    order: "Custom Order",
    inventory: "existing inventory",
  },
  {
    id: 2,
    title: "Model X",
    description: "Order Online for",
    delivery: "Touchless Delivery",
    image: "images/model-x.jpg",
    range: "350",
    time: "1.55",
    topSpeed: "150",
    peakPower: "1,130",
    order: "Custom Order",
    inventory: "existing inventory",
  },
  {
    id: 3,
    title: "Model Y",
    description: "Order Online for",
    delivery: "Touchless Delivery",
    image: "images/model-y.jpg",
    range: "410",
    time: "2.05",
    topSpeed: "190",
    peakPower: "1,040",
    order: "Custom Order",
    inventory: "existing inventory",
  },
  {
    id: 4,
    title: "Solar Panels",
    description: "Lowest Cost Solar Panels in America",
    image: "images/solar-panel.jpg",
    range: "390",
    time: "1.99",
    topSpeed: "200",
    peakPower: "1,020",
    order: "Order Now",
    inventory: "learn more",
  },
  {
    id: 5,
    title: "Solar Roof",
    description: "Produce Clean Energy From Your Roof",
    image: "images/solar-roof.jpg",
    range: "390",
    time: "1.99",
    topSpeed: "200",
    peakPower: "1,020",
    order: "Order Now",
    inventory: "learn more",
  },
  {
    id: 6,
    title: "Accessories",
    image: "images/accessories.jpg",
    range: "390",
    time: "1.99",
    topSpeed: "200",
    peakPower: "1,020",
    order: "Shop Now",
  },
];

export default Cars;
